# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Jun  4 02:07:18 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(712, 426)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Desktop/vehicle2.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.ThrustersInitialize = QtGui.QPushButton(self.centralWidget)
        self.ThrustersInitialize.setGeometry(QtCore.QRect(100, 10, 141, 27))
        self.ThrustersInitialize.setObjectName(_fromUtf8("ThrustersInitialize"))
        self.ThrustersOn = QtGui.QPushButton(self.centralWidget)
        self.ThrustersOn.setGeometry(QtCore.QRect(110, 50, 111, 27))
        self.ThrustersOn.setObjectName(_fromUtf8("ThrustersOn"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 110, 81, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 81, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 71, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 67, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.front_pitch_slider = QtGui.QSlider(self.centralWidget)
        self.front_pitch_slider.setGeometry(QtCore.QRect(110, 110, 181, 29))
        self.front_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.front_pitch_slider.setObjectName(_fromUtf8("front_pitch_slider"))
        self.back_pitch_slider = QtGui.QSlider(self.centralWidget)
        self.back_pitch_slider.setGeometry(QtCore.QRect(110, 150, 181, 29))
        self.back_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.back_pitch_slider.setObjectName(_fromUtf8("back_pitch_slider"))
        self.side_left_slider = QtGui.QSlider(self.centralWidget)
        self.side_left_slider.setGeometry(QtCore.QRect(110, 190, 181, 29))
        self.side_left_slider.setOrientation(QtCore.Qt.Horizontal)
        self.side_left_slider.setObjectName(_fromUtf8("side_left_slider"))
        self.side_right_slider = QtGui.QSlider(self.centralWidget)
        self.side_right_slider.setGeometry(QtCore.QRect(110, 230, 181, 29))
        self.side_right_slider.setOrientation(QtCore.Qt.Horizontal)
        self.side_right_slider.setObjectName(_fromUtf8("side_right_slider"))
        self.errorboard = QtGui.QTextBrowser(self.centralWidget)
        self.errorboard.setGeometry(QtCore.QRect(370, 60, 211, 181))
        self.errorboard.setObjectName(_fromUtf8("errorboard"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(370, 30, 111, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.powerupOBC = QtGui.QPushButton(self.centralWidget)
        self.powerupOBC.setGeometry(QtCore.QRect(590, 60, 101, 27))
        self.powerupOBC.setObjectName(_fromUtf8("powerupOBC"))
        self.poweroffOBC = QtGui.QPushButton(self.centralWidget)
        self.poweroffOBC.setGeometry(QtCore.QRect(590, 120, 111, 27))
        self.poweroffOBC.setObjectName(_fromUtf8("poweroffOBC"))
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(10, 290, 681, 61))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.rfront_pitch = QtGui.QPushButton(self.frame)
        self.rfront_pitch.setGeometry(QtCore.QRect(40, 20, 99, 27))
        self.rfront_pitch.setObjectName(_fromUtf8("rfront_pitch"))
        self.rback_pitch = QtGui.QPushButton(self.frame)
        self.rback_pitch.setGeometry(QtCore.QRect(210, 20, 99, 27))
        self.rback_pitch.setObjectName(_fromUtf8("rback_pitch"))
        self.rside_left = QtGui.QPushButton(self.frame)
        self.rside_left.setGeometry(QtCore.QRect(380, 20, 99, 27))
        self.rside_left.setObjectName(_fromUtf8("rside_left"))
        self.rside_right = QtGui.QPushButton(self.frame)
        self.rside_right.setGeometry(QtCore.QRect(540, 20, 99, 27))
        self.rside_right.setObjectName(_fromUtf8("rside_right"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(250, 260, 191, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.OBCon = QtGui.QPushButton(self.centralWidget)
        self.OBCon.setGeometry(QtCore.QRect(590, 170, 99, 27))
        self.OBCon.setObjectName(_fromUtf8("OBCon"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(110, 90, 21, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(270, 90, 31, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.front_pitch_val = QtGui.QLabel(self.centralWidget)
        self.front_pitch_val.setGeometry(QtCore.QRect(330, 110, 31, 20))
        self.front_pitch_val.setObjectName(_fromUtf8("front_pitch_val"))
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(110, 140, 16, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(270, 140, 67, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.back_pitch_val = QtGui.QLabel(self.centralWidget)
        self.back_pitch_val.setGeometry(QtCore.QRect(330, 160, 31, 17))
        self.back_pitch_val.setObjectName(_fromUtf8("back_pitch_val"))
        self.label_13 = QtGui.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(110, 180, 16, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(270, 180, 31, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.side_left_val = QtGui.QLabel(self.centralWidget)
        self.side_left_val.setGeometry(QtCore.QRect(330, 190, 31, 17))
        self.side_left_val.setObjectName(_fromUtf8("side_left_val"))
        self.label_16 = QtGui.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(110, 220, 16, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.centralWidget)
        self.label_17.setGeometry(QtCore.QRect(280, 220, 31, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.side_right_val = QtGui.QLabel(self.centralWidget)
        self.side_right_val.setGeometry(QtCore.QRect(330, 230, 31, 17))
        self.side_right_val.setObjectName(_fromUtf8("side_right_val"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 712, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Thruster Panel", None))
        MainWindow.setToolTip(_translate("MainWindow", "Thruster_Panel", None))
        self.ThrustersInitialize.setText(_translate("MainWindow", "Thrusters Initialize", None))
        self.ThrustersOn.setText(_translate("MainWindow", "Thrusters On", None))
        self.label.setText(_translate("MainWindow", "front_pitch", None))
        self.label_2.setText(_translate("MainWindow", "back_pitch", None))
        self.label_3.setText(_translate("MainWindow", "side_left", None))
        self.label_4.setText(_translate("MainWindow", "side_right", None))
        self.label_5.setText(_translate("MainWindow", "Error notice!!!!", None))
        self.powerupOBC.setText(_translate("MainWindow", "powerup-OBC", None))
        self.poweroffOBC.setText(_translate("MainWindow", "Poweroff-OBC", None))
        self.rfront_pitch.setText(_translate("MainWindow", "front_pitch", None))
        self.rback_pitch.setText(_translate("MainWindow", "back_pitch", None))
        self.rside_left.setText(_translate("MainWindow", "side_left", None))
        self.rside_right.setText(_translate("MainWindow", "side_right", None))
        self.label_6.setText(_translate("MainWindow", "Thruster Direction  Reverse", None))
        self.OBCon.setText(_translate("MainWindow", "OBC-on", None))
        self.label_7.setText(_translate("MainWindow", "0", None))
        self.label_8.setText(_translate("MainWindow", "179", None))
        self.front_pitch_val.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "0", None))
        self.label_11.setText(_translate("MainWindow", "179", None))
        self.back_pitch_val.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "0", None))
        self.label_14.setText(_translate("MainWindow", "179", None))
        self.side_left_val.setText(_translate("MainWindow", "0", None))
        self.label_16.setText(_translate("MainWindow", "0", None))
        self.label_17.setText(_translate("MainWindow", "179", None))
        self.side_right_val.setText(_translate("MainWindow", "0", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Jul 16 00:44:07 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(712, 426)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Desktop/vehicle2.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.ThrustersInitialize = QtGui.QPushButton(self.centralWidget)
        self.ThrustersInitialize.setGeometry(QtCore.QRect(100, 10, 141, 27))
        self.ThrustersInitialize.setObjectName(_fromUtf8("ThrustersInitialize"))
        self.ThrustersOn = QtGui.QPushButton(self.centralWidget)
        self.ThrustersOn.setGeometry(QtCore.QRect(110, 50, 111, 27))
        self.ThrustersOn.setObjectName(_fromUtf8("ThrustersOn"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 110, 81, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 81, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 71, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 67, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.front_pitch_slider = QtGui.QSlider(self.centralWidget)
        self.front_pitch_slider.setGeometry(QtCore.QRect(110, 110, 181, 29))
        self.front_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.front_pitch_slider.setObjectName(_fromUtf8("front_pitch_slider"))
        self.back_pitch_slider = QtGui.QSlider(self.centralWidget)
        self.back_pitch_slider.setGeometry(QtCore.QRect(110, 150, 181, 29))
        self.back_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.back_pitch_slider.setObjectName(_fromUtf8("back_pitch_slider"))
        self.side_left_slider = QtGui.QSlider(self.centralWidget)
        self.side_left_slider.setGeometry(QtCore.QRect(110, 190, 181, 29))
        self.side_left_slider.setOrientation(QtCore.Qt.Horizontal)
        self.side_left_slider.setObjectName(_fromUtf8("side_left_slider"))
        self.side_right_slider = QtGui.QSlider(self.centralWidget)
        self.side_right_slider.setGeometry(QtCore.QRect(110, 230, 181, 29))
        self.side_right_slider.setOrientation(QtCore.Qt.Horizontal)
        self.side_right_slider.setObjectName(_fromUtf8("side_right_slider"))
        self.errorboard = QtGui.QTextBrowser(self.centralWidget)
        self.errorboard.setGeometry(QtCore.QRect(370, 60, 211, 181))
        self.errorboard.setObjectName(_fromUtf8("errorboard"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(370, 30, 111, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.powerupOBC = QtGui.QPushButton(self.centralWidget)
        self.powerupOBC.setGeometry(QtCore.QRect(590, 60, 101, 27))
        self.powerupOBC.setObjectName(_fromUtf8("powerupOBC"))
        self.poweroffOBC = QtGui.QPushButton(self.centralWidget)
        self.poweroffOBC.setGeometry(QtCore.QRect(590, 120, 111, 27))
        self.poweroffOBC.setObjectName(_fromUtf8("poweroffOBC"))
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(10, 290, 681, 61))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.rfront_pitch = QtGui.QPushButton(self.frame)
        self.rfront_pitch.setGeometry(QtCore.QRect(40, 20, 99, 27))
        self.rfront_pitch.setObjectName(_fromUtf8("rfront_pitch"))
        self.rback_pitch = QtGui.QPushButton(self.frame)
        self.rback_pitch.setGeometry(QtCore.QRect(210, 20, 99, 27))
        self.rback_pitch.setObjectName(_fromUtf8("rback_pitch"))
        self.rside_left = QtGui.QPushButton(self.frame)
        self.rside_left.setGeometry(QtCore.QRect(380, 20, 99, 27))
        self.rside_left.setObjectName(_fromUtf8("rside_left"))
        self.rside_right = QtGui.QPushButton(self.frame)
        self.rside_right.setGeometry(QtCore.QRect(540, 20, 99, 27))
        self.rside_right.setObjectName(_fromUtf8("rside_right"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(250, 260, 191, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.OBCon = QtGui.QPushButton(self.centralWidget)
        self.OBCon.setGeometry(QtCore.QRect(590, 170, 99, 27))
        self.OBCon.setObjectName(_fromUtf8("OBCon"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(110, 90, 31, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(270, 90, 41, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.front_pitch_val = QtGui.QLabel(self.centralWidget)
        self.front_pitch_val.setGeometry(QtCore.QRect(330, 110, 31, 20))
        self.front_pitch_val.setObjectName(_fromUtf8("front_pitch_val"))
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(110, 140, 31, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(270, 140, 67, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.back_pitch_val = QtGui.QLabel(self.centralWidget)
        self.back_pitch_val.setGeometry(QtCore.QRect(330, 160, 31, 17))
        self.back_pitch_val.setObjectName(_fromUtf8("back_pitch_val"))
        self.label_13 = QtGui.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(110, 180, 41, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(270, 180, 41, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.side_left_val = QtGui.QLabel(self.centralWidget)
        self.side_left_val.setGeometry(QtCore.QRect(330, 190, 31, 17))
        self.side_left_val.setObjectName(_fromUtf8("side_left_val"))
        self.label_16 = QtGui.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(110, 220, 31, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.centralWidget)
        self.label_17.setGeometry(QtCore.QRect(280, 220, 41, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.side_right_val = QtGui.QLabel(self.centralWidget)
        self.side_right_val.setGeometry(QtCore.QRect(330, 230, 31, 17))
        self.side_right_val.setObjectName(_fromUtf8("side_right_val"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 712, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Thruster Panel", None))
        MainWindow.setToolTip(_translate("MainWindow", "Thruster_Panel", None))
        self.ThrustersInitialize.setText(_translate("MainWindow", "Thrusters Initialize", None))
        self.ThrustersOn.setText(_translate("MainWindow", "Thrusters On", None))
        self.label.setText(_translate("MainWindow", "front_pitch", None))
        self.label_2.setText(_translate("MainWindow", "back_pitch", None))
        self.label_3.setText(_translate("MainWindow", "side_left", None))
        self.label_4.setText(_translate("MainWindow", "side_right", None))
        self.label_5.setText(_translate("MainWindow", "Error notice!!!!", None))
        self.powerupOBC.setText(_translate("MainWindow", "powerup-OBC", None))
        self.poweroffOBC.setText(_translate("MainWindow", "Poweroff-OBC", None))
        self.rfront_pitch.setText(_translate("MainWindow", "front_pitch", None))
        self.rback_pitch.setText(_translate("MainWindow", "back_pitch", None))
        self.rside_left.setText(_translate("MainWindow", "side_left", None))
        self.rside_right.setText(_translate("MainWindow", "side_right", None))
        self.label_6.setText(_translate("MainWindow", "Thruster Direction  Reverse", None))
        self.OBCon.setText(_translate("MainWindow", "OBC-on", None))
        self.label_7.setText(_translate("MainWindow", "992", None))
        self.label_8.setText(_translate("MainWindow", "2000", None))
        self.front_pitch_val.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "992", None))
        self.label_11.setText(_translate("MainWindow", "2000", None))
        self.back_pitch_val.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "992", None))
        self.label_14.setText(_translate("MainWindow", "2000", None))
        self.side_left_val.setText(_translate("MainWindow", "0", None))
        self.label_16.setText(_translate("MainWindow", "992", None))
        self.label_17.setText(_translate("MainWindow", "2000", None))
        self.side_right_val.setText(_translate("MainWindow", "0", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Jul 16 00:44:25 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(712, 426)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Desktop/vehicle2.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.ThrustersInitialize = QtGui.QPushButton(self.centralWidget)
        self.ThrustersInitialize.setGeometry(QtCore.QRect(100, 10, 141, 27))
        self.ThrustersInitialize.setObjectName(_fromUtf8("ThrustersInitialize"))
        self.ThrustersOn = QtGui.QPushButton(self.centralWidget)
        self.ThrustersOn.setGeometry(QtCore.QRect(110, 50, 111, 27))
        self.ThrustersOn.setObjectName(_fromUtf8("ThrustersOn"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 110, 81, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 81, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 71, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 67, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.front_pitch_slider = QtGui.QSlider(self.centralWidget)
        self.front_pitch_slider.setGeometry(QtCore.QRect(110, 110, 181, 29))
        self.front_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.front_pitch_slider.setObjectName(_fromUtf8("front_pitch_slider"))
        self.back_pitch_slider = QtGui.QSlider(self.centralWidget)
        self.back_pitch_slider.setGeometry(QtCore.QRect(110, 150, 181, 29))
        self.back_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.back_pitch_slider.setObjectName(_fromUtf8("back_pitch_slider"))
        self.side_left_slider = QtGui.QSlider(self.centralWidget)
        self.side_left_slider.setGeometry(QtCore.QRect(110, 190, 181, 29))
        self.side_left_slider.setOrientation(QtCore.Qt.Horizontal)
        self.side_left_slider.setObjectName(_fromUtf8("side_left_slider"))
        self.side_right_slider = QtGui.QSlider(self.centralWidget)
        self.side_right_slider.setGeometry(QtCore.QRect(110, 230, 181, 29))
        self.side_right_slider.setOrientation(QtCore.Qt.Horizontal)
        self.side_right_slider.setObjectName(_fromUtf8("side_right_slider"))
        self.errorboard = QtGui.QTextBrowser(self.centralWidget)
        self.errorboard.setGeometry(QtCore.QRect(370, 60, 211, 181))
        self.errorboard.setObjectName(_fromUtf8("errorboard"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(370, 30, 111, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.powerupOBC = QtGui.QPushButton(self.centralWidget)
        self.powerupOBC.setGeometry(QtCore.QRect(590, 60, 101, 27))
        self.powerupOBC.setObjectName(_fromUtf8("powerupOBC"))
        self.poweroffOBC = QtGui.QPushButton(self.centralWidget)
        self.poweroffOBC.setGeometry(QtCore.QRect(590, 120, 111, 27))
        self.poweroffOBC.setObjectName(_fromUtf8("poweroffOBC"))
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(10, 290, 681, 61))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.rfront_pitch = QtGui.QPushButton(self.frame)
        self.rfront_pitch.setGeometry(QtCore.QRect(40, 20, 99, 27))
        self.rfront_pitch.setObjectName(_fromUtf8("rfront_pitch"))
        self.rback_pitch = QtGui.QPushButton(self.frame)
        self.rback_pitch.setGeometry(QtCore.QRect(210, 20, 99, 27))
        self.rback_pitch.setObjectName(_fromUtf8("rback_pitch"))
        self.rside_left = QtGui.QPushButton(self.frame)
        self.rside_left.setGeometry(QtCore.QRect(380, 20, 99, 27))
        self.rside_left.setObjectName(_fromUtf8("rside_left"))
        self.rside_right = QtGui.QPushButton(self.frame)
        self.rside_right.setGeometry(QtCore.QRect(540, 20, 99, 27))
        self.rside_right.setObjectName(_fromUtf8("rside_right"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(250, 260, 191, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.OBCon = QtGui.QPushButton(self.centralWidget)
        self.OBCon.setGeometry(QtCore.QRect(590, 170, 99, 27))
        self.OBCon.setObjectName(_fromUtf8("OBCon"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(110, 90, 31, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(270, 90, 41, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.front_pitch_val = QtGui.QLabel(self.centralWidget)
        self.front_pitch_val.setGeometry(QtCore.QRect(330, 110, 31, 20))
        self.front_pitch_val.setObjectName(_fromUtf8("front_pitch_val"))
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(110, 140, 31, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(270, 140, 67, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.back_pitch_val = QtGui.QLabel(self.centralWidget)
        self.back_pitch_val.setGeometry(QtCore.QRect(330, 160, 31, 17))
        self.back_pitch_val.setObjectName(_fromUtf8("back_pitch_val"))
        self.label_13 = QtGui.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(110, 180, 41, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(270, 180, 41, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.side_left_val = QtGui.QLabel(self.centralWidget)
        self.side_left_val.setGeometry(QtCore.QRect(330, 190, 31, 17))
        self.side_left_val.setObjectName(_fromUtf8("side_left_val"))
        self.label_16 = QtGui.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(110, 220, 31, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.centralWidget)
        self.label_17.setGeometry(QtCore.QRect(280, 220, 41, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.side_right_val = QtGui.QLabel(self.centralWidget)
        self.side_right_val.setGeometry(QtCore.QRect(330, 230, 31, 17))
        self.side_right_val.setObjectName(_fromUtf8("side_right_val"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 712, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Thruster Panel", None))
        MainWindow.setToolTip(_translate("MainWindow", "Thruster_Panel", None))
        self.ThrustersInitialize.setText(_translate("MainWindow", "Thrusters Initialize", None))
        self.ThrustersOn.setText(_translate("MainWindow", "Thrusters On", None))
        self.label.setText(_translate("MainWindow", "front_pitch", None))
        self.label_2.setText(_translate("MainWindow", "back_pitch", None))
        self.label_3.setText(_translate("MainWindow", "side_left", None))
        self.label_4.setText(_translate("MainWindow", "side_right", None))
        self.label_5.setText(_translate("MainWindow", "Error notice!!!!", None))
        self.powerupOBC.setText(_translate("MainWindow", "powerup-OBC", None))
        self.poweroffOBC.setText(_translate("MainWindow", "Poweroff-OBC", None))
        self.rfront_pitch.setText(_translate("MainWindow", "front_pitch", None))
        self.rback_pitch.setText(_translate("MainWindow", "back_pitch", None))
        self.rside_left.setText(_translate("MainWindow", "side_left", None))
        self.rside_right.setText(_translate("MainWindow", "side_right", None))
        self.label_6.setText(_translate("MainWindow", "Thruster Direction  Reverse", None))
        self.OBCon.setText(_translate("MainWindow", "OBC-on", None))
        self.label_7.setText(_translate("MainWindow", "992", None))
        self.label_8.setText(_translate("MainWindow", "2000", None))
        self.front_pitch_val.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "992", None))
        self.label_11.setText(_translate("MainWindow", "2000", None))
        self.back_pitch_val.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "992", None))
        self.label_14.setText(_translate("MainWindow", "2000", None))
        self.side_left_val.setText(_translate("MainWindow", "0", None))
        self.label_16.setText(_translate("MainWindow", "992", None))
        self.label_17.setText(_translate("MainWindow", "2000", None))
        self.side_right_val.setText(_translate("MainWindow", "0", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Jul 19 05:23:53 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(712, 426)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Desktop/vehicle2.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.ThrustersInitialize = QtGui.QPushButton(self.centralWidget)
        self.ThrustersInitialize.setGeometry(QtCore.QRect(100, 10, 141, 27))
        self.ThrustersInitialize.setObjectName(_fromUtf8("ThrustersInitialize"))
        self.ThrustersOn = QtGui.QPushButton(self.centralWidget)
        self.ThrustersOn.setGeometry(QtCore.QRect(40, 50, 111, 27))
        self.ThrustersOn.setObjectName(_fromUtf8("ThrustersOn"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 110, 81, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 81, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 71, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 67, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.front_pitch_slider = QtGui.QSlider(self.centralWidget)
        self.front_pitch_slider.setGeometry(QtCore.QRect(110, 110, 181, 29))
        self.front_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.front_pitch_slider.setObjectName(_fromUtf8("front_pitch_slider"))
        self.back_pitch_slider = QtGui.QSlider(self.centralWidget)
        self.back_pitch_slider.setGeometry(QtCore.QRect(110, 150, 181, 29))
        self.back_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.back_pitch_slider.setObjectName(_fromUtf8("back_pitch_slider"))
        self.side_left_slider = QtGui.QSlider(self.centralWidget)
        self.side_left_slider.setGeometry(QtCore.QRect(110, 190, 181, 29))
        self.side_left_slider.setOrientation(QtCore.Qt.Horizontal)
        self.side_left_slider.setObjectName(_fromUtf8("side_left_slider"))
        self.side_right_slider = QtGui.QSlider(self.centralWidget)
        self.side_right_slider.setGeometry(QtCore.QRect(110, 230, 181, 29))
        self.side_right_slider.setOrientation(QtCore.Qt.Horizontal)
        self.side_right_slider.setObjectName(_fromUtf8("side_right_slider"))
        self.errorboard = QtGui.QTextBrowser(self.centralWidget)
        self.errorboard.setGeometry(QtCore.QRect(370, 60, 211, 181))
        self.errorboard.setObjectName(_fromUtf8("errorboard"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(370, 30, 111, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.powerupOBC = QtGui.QPushButton(self.centralWidget)
        self.powerupOBC.setGeometry(QtCore.QRect(210, 50, 101, 27))
        self.powerupOBC.setObjectName(_fromUtf8("powerupOBC"))
        self.poweroffOBC = QtGui.QPushButton(self.centralWidget)
        self.poweroffOBC.setGeometry(QtCore.QRect(590, 120, 111, 27))
        self.poweroffOBC.setObjectName(_fromUtf8("poweroffOBC"))
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(10, 290, 681, 61))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.rfront_pitch = QtGui.QPushButton(self.frame)
        self.rfront_pitch.setGeometry(QtCore.QRect(40, 20, 99, 27))
        self.rfront_pitch.setObjectName(_fromUtf8("rfront_pitch"))
        self.rback_pitch = QtGui.QPushButton(self.frame)
        self.rback_pitch.setGeometry(QtCore.QRect(210, 20, 99, 27))
        self.rback_pitch.setObjectName(_fromUtf8("rback_pitch"))
        self.rside_left = QtGui.QPushButton(self.frame)
        self.rside_left.setGeometry(QtCore.QRect(380, 20, 99, 27))
        self.rside_left.setObjectName(_fromUtf8("rside_left"))
        self.rside_right = QtGui.QPushButton(self.frame)
        self.rside_right.setGeometry(QtCore.QRect(540, 20, 99, 27))
        self.rside_right.setObjectName(_fromUtf8("rside_right"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(250, 260, 191, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.OBCon = QtGui.QPushButton(self.centralWidget)
        self.OBCon.setGeometry(QtCore.QRect(590, 170, 99, 27))
        self.OBCon.setObjectName(_fromUtf8("OBCon"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(110, 90, 31, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(270, 90, 41, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.front_pitch_val = QtGui.QLabel(self.centralWidget)
        self.front_pitch_val.setGeometry(QtCore.QRect(330, 110, 31, 20))
        self.front_pitch_val.setObjectName(_fromUtf8("front_pitch_val"))
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(110, 140, 31, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(270, 140, 67, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.back_pitch_val = QtGui.QLabel(self.centralWidget)
        self.back_pitch_val.setGeometry(QtCore.QRect(330, 160, 31, 17))
        self.back_pitch_val.setObjectName(_fromUtf8("back_pitch_val"))
        self.label_13 = QtGui.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(110, 180, 41, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(270, 180, 41, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.side_left_val = QtGui.QLabel(self.centralWidget)
        self.side_left_val.setGeometry(QtCore.QRect(330, 190, 31, 17))
        self.side_left_val.setObjectName(_fromUtf8("side_left_val"))
        self.label_16 = QtGui.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(110, 220, 31, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.centralWidget)
        self.label_17.setGeometry(QtCore.QRect(280, 220, 41, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.side_right_val = QtGui.QLabel(self.centralWidget)
        self.side_right_val.setGeometry(QtCore.QRect(330, 230, 31, 17))
        self.side_right_val.setObjectName(_fromUtf8("side_right_val"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 712, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Thruster Panel", None))
        MainWindow.setToolTip(_translate("MainWindow", "Thruster_Panel", None))
        self.ThrustersInitialize.setText(_translate("MainWindow", "Thrusters Initialize", None))
        self.ThrustersOn.setText(_translate("MainWindow", "Thrusters On", None))
        self.label.setText(_translate("MainWindow", "front_pitch", None))
        self.label_2.setText(_translate("MainWindow", "back_pitch", None))
        self.label_3.setText(_translate("MainWindow", "side_left", None))
        self.label_4.setText(_translate("MainWindow", "side_right", None))
        self.label_5.setText(_translate("MainWindow", "Error notice!!!!", None))
        self.powerupOBC.setText(_translate("MainWindow", "Thrusters off", None))
        self.poweroffOBC.setText(_translate("MainWindow", "Poweroff-OBC", None))
        self.rfront_pitch.setText(_translate("MainWindow", "front_pitch", None))
        self.rback_pitch.setText(_translate("MainWindow", "back_pitch", None))
        self.rside_left.setText(_translate("MainWindow", "side_left", None))
        self.rside_right.setText(_translate("MainWindow", "side_right", None))
        self.label_6.setText(_translate("MainWindow", "Thruster Direction  Reverse", None))
        self.OBCon.setText(_translate("MainWindow", "OBC-on", None))
        self.label_7.setText(_translate("MainWindow", "992", None))
        self.label_8.setText(_translate("MainWindow", "2000", None))
        self.front_pitch_val.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "992", None))
        self.label_11.setText(_translate("MainWindow", "2000", None))
        self.back_pitch_val.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "992", None))
        self.label_14.setText(_translate("MainWindow", "2000", None))
        self.side_left_val.setText(_translate("MainWindow", "0", None))
        self.label_16.setText(_translate("MainWindow", "992", None))
        self.label_17.setText(_translate("MainWindow", "2000", None))
        self.side_right_val.setText(_translate("MainWindow", "0", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Jul 19 05:25:37 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(712, 426)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Desktop/vehicle2.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.ThrustersInitialize = QtGui.QPushButton(self.centralWidget)
        self.ThrustersInitialize.setGeometry(QtCore.QRect(100, 10, 141, 27))
        self.ThrustersInitialize.setObjectName(_fromUtf8("ThrustersInitialize"))
        self.ThrustersOn = QtGui.QPushButton(self.centralWidget)
        self.ThrustersOn.setGeometry(QtCore.QRect(40, 50, 111, 27))
        self.ThrustersOn.setObjectName(_fromUtf8("ThrustersOn"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 110, 81, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 81, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 71, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 67, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.front_pitch_slider = QtGui.QSlider(self.centralWidget)
        self.front_pitch_slider.setGeometry(QtCore.QRect(110, 110, 181, 29))
        self.front_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.front_pitch_slider.setObjectName(_fromUtf8("front_pitch_slider"))
        self.back_pitch_slider = QtGui.QSlider(self.centralWidget)
        self.back_pitch_slider.setGeometry(QtCore.QRect(110, 150, 181, 29))
        self.back_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.back_pitch_slider.setObjectName(_fromUtf8("back_pitch_slider"))
        self.side_left_slider = QtGui.QSlider(self.centralWidget)
        self.side_left_slider.setGeometry(QtCore.QRect(110, 190, 181, 29))
        self.side_left_slider.setOrientation(QtCore.Qt.Horizontal)
        self.side_left_slider.setObjectName(_fromUtf8("side_left_slider"))
        self.side_right_slider = QtGui.QSlider(self.centralWidget)
        self.side_right_slider.setGeometry(QtCore.QRect(110, 230, 181, 29))
        self.side_right_slider.setOrientation(QtCore.Qt.Horizontal)
        self.side_right_slider.setObjectName(_fromUtf8("side_right_slider"))
        self.errorboard = QtGui.QTextBrowser(self.centralWidget)
        self.errorboard.setGeometry(QtCore.QRect(370, 60, 211, 181))
        self.errorboard.setObjectName(_fromUtf8("errorboard"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(370, 30, 111, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.powerupOBC = QtGui.QPushButton(self.centralWidget)
        self.powerupOBC.setGeometry(QtCore.QRect(210, 50, 101, 27))
        self.powerupOBC.setObjectName(_fromUtf8("powerupOBC"))
        self.poweroffOBC = QtGui.QPushButton(self.centralWidget)
        self.poweroffOBC.setGeometry(QtCore.QRect(590, 120, 111, 27))
        self.poweroffOBC.setObjectName(_fromUtf8("poweroffOBC"))
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(10, 290, 681, 61))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.rfront_pitch = QtGui.QPushButton(self.frame)
        self.rfront_pitch.setGeometry(QtCore.QRect(40, 20, 99, 27))
        self.rfront_pitch.setObjectName(_fromUtf8("rfront_pitch"))
        self.rback_pitch = QtGui.QPushButton(self.frame)
        self.rback_pitch.setGeometry(QtCore.QRect(210, 20, 99, 27))
        self.rback_pitch.setObjectName(_fromUtf8("rback_pitch"))
        self.rside_left = QtGui.QPushButton(self.frame)
        self.rside_left.setGeometry(QtCore.QRect(380, 20, 99, 27))
        self.rside_left.setObjectName(_fromUtf8("rside_left"))
        self.rside_right = QtGui.QPushButton(self.frame)
        self.rside_right.setGeometry(QtCore.QRect(540, 20, 99, 27))
        self.rside_right.setObjectName(_fromUtf8("rside_right"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(250, 260, 191, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.OBCon = QtGui.QPushButton(self.centralWidget)
        self.OBCon.setGeometry(QtCore.QRect(590, 170, 99, 27))
        self.OBCon.setObjectName(_fromUtf8("OBCon"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(110, 90, 31, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(270, 90, 41, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.front_pitch_val = QtGui.QLabel(self.centralWidget)
        self.front_pitch_val.setGeometry(QtCore.QRect(330, 110, 31, 20))
        self.front_pitch_val.setObjectName(_fromUtf8("front_pitch_val"))
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(110, 140, 31, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(270, 140, 67, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.back_pitch_val = QtGui.QLabel(self.centralWidget)
        self.back_pitch_val.setGeometry(QtCore.QRect(330, 160, 31, 17))
        self.back_pitch_val.setObjectName(_fromUtf8("back_pitch_val"))
        self.label_13 = QtGui.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(110, 180, 41, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(270, 180, 41, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.side_left_val = QtGui.QLabel(self.centralWidget)
        self.side_left_val.setGeometry(QtCore.QRect(330, 190, 31, 17))
        self.side_left_val.setObjectName(_fromUtf8("side_left_val"))
        self.label_16 = QtGui.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(110, 220, 31, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.centralWidget)
        self.label_17.setGeometry(QtCore.QRect(280, 220, 41, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.side_right_val = QtGui.QLabel(self.centralWidget)
        self.side_right_val.setGeometry(QtCore.QRect(330, 230, 31, 17))
        self.side_right_val.setObjectName(_fromUtf8("side_right_val"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 712, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Thruster Panel", None))
        MainWindow.setToolTip(_translate("MainWindow", "Thruster_Panel", None))
        self.ThrustersInitialize.setText(_translate("MainWindow", "Thrusters Initialize", None))
        self.ThrustersOn.setText(_translate("MainWindow", "Thrusters On", None))
        self.label.setText(_translate("MainWindow", "front_pitch", None))
        self.label_2.setText(_translate("MainWindow", "back_pitch", None))
        self.label_3.setText(_translate("MainWindow", "side_left", None))
        self.label_4.setText(_translate("MainWindow", "side_right", None))
        self.label_5.setText(_translate("MainWindow", "Error notice!!!!", None))
        self.powerupOBC.setText(_translate("MainWindow", "Thrusters off", None))
        self.poweroffOBC.setText(_translate("MainWindow", "Poweroff-OBC", None))
        self.rfront_pitch.setText(_translate("MainWindow", "front_pitch", None))
        self.rback_pitch.setText(_translate("MainWindow", "back_pitch", None))
        self.rside_left.setText(_translate("MainWindow", "side_left", None))
        self.rside_right.setText(_translate("MainWindow", "side_right", None))
        self.label_6.setText(_translate("MainWindow", "Thruster Direction  Reverse", None))
        self.OBCon.setText(_translate("MainWindow", "OBC-on", None))
        self.label_7.setText(_translate("MainWindow", "992", None))
        self.label_8.setText(_translate("MainWindow", "2000", None))
        self.front_pitch_val.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "992", None))
        self.label_11.setText(_translate("MainWindow", "2000", None))
        self.back_pitch_val.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "992", None))
        self.label_14.setText(_translate("MainWindow", "2000", None))
        self.side_left_val.setText(_translate("MainWindow", "0", None))
        self.label_16.setText(_translate("MainWindow", "992", None))
        self.label_17.setText(_translate("MainWindow", "2000", None))
        self.side_right_val.setText(_translate("MainWindow", "0", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Jul 19 05:27:59 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(712, 426)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Desktop/vehicle2.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.ThrustersInitialize = QtGui.QPushButton(self.centralWidget)
        self.ThrustersInitialize.setGeometry(QtCore.QRect(100, 10, 141, 27))
        self.ThrustersInitialize.setObjectName(_fromUtf8("ThrustersInitialize"))
        self.ThrustersOn = QtGui.QPushButton(self.centralWidget)
        self.ThrustersOn.setGeometry(QtCore.QRect(40, 50, 111, 27))
        self.ThrustersOn.setObjectName(_fromUtf8("ThrustersOn"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 110, 81, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 81, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 71, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 67, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.front_pitch_slider = QtGui.QSlider(self.centralWidget)
        self.front_pitch_slider.setGeometry(QtCore.QRect(110, 110, 181, 29))
        self.front_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.front_pitch_slider.setObjectName(_fromUtf8("front_pitch_slider"))
        self.back_pitch_slider = QtGui.QSlider(self.centralWidget)
        self.back_pitch_slider.setGeometry(QtCore.QRect(110, 150, 181, 29))
        self.back_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.back_pitch_slider.setObjectName(_fromUtf8("back_pitch_slider"))
        self.side_left_slider = QtGui.QSlider(self.centralWidget)
        self.side_left_slider.setGeometry(QtCore.QRect(110, 190, 181, 29))
        self.side_left_slider.setOrientation(QtCore.Qt.Horizontal)
        self.side_left_slider.setObjectName(_fromUtf8("side_left_slider"))
        self.side_right_slider = QtGui.QSlider(self.centralWidget)
        self.side_right_slider.setGeometry(QtCore.QRect(110, 230, 181, 29))
        self.side_right_slider.setOrientation(QtCore.Qt.Horizontal)
        self.side_right_slider.setObjectName(_fromUtf8("side_right_slider"))
        self.errorboard = QtGui.QTextBrowser(self.centralWidget)
        self.errorboard.setGeometry(QtCore.QRect(370, 60, 211, 181))
        self.errorboard.setObjectName(_fromUtf8("errorboard"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(370, 30, 111, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.Thrustersoff = QtGui.QPushButton(self.centralWidget)
        self.Thrustersoff.setGeometry(QtCore.QRect(210, 50, 101, 27))
        self.Thrustersoff.setObjectName(_fromUtf8("Thrustersoff"))
        self.poweroffOBC = QtGui.QPushButton(self.centralWidget)
        self.poweroffOBC.setGeometry(QtCore.QRect(590, 120, 111, 27))
        self.poweroffOBC.setObjectName(_fromUtf8("poweroffOBC"))
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(10, 290, 681, 61))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.rfront_pitch = QtGui.QPushButton(self.frame)
        self.rfront_pitch.setGeometry(QtCore.QRect(40, 20, 99, 27))
        self.rfront_pitch.setObjectName(_fromUtf8("rfront_pitch"))
        self.rback_pitch = QtGui.QPushButton(self.frame)
        self.rback_pitch.setGeometry(QtCore.QRect(210, 20, 99, 27))
        self.rback_pitch.setObjectName(_fromUtf8("rback_pitch"))
        self.rside_left = QtGui.QPushButton(self.frame)
        self.rside_left.setGeometry(QtCore.QRect(380, 20, 99, 27))
        self.rside_left.setObjectName(_fromUtf8("rside_left"))
        self.rside_right = QtGui.QPushButton(self.frame)
        self.rside_right.setGeometry(QtCore.QRect(540, 20, 99, 27))
        self.rside_right.setObjectName(_fromUtf8("rside_right"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(250, 260, 191, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.OBCon = QtGui.QPushButton(self.centralWidget)
        self.OBCon.setGeometry(QtCore.QRect(590, 170, 99, 27))
        self.OBCon.setObjectName(_fromUtf8("OBCon"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(110, 90, 31, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(270, 90, 41, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.front_pitch_val = QtGui.QLabel(self.centralWidget)
        self.front_pitch_val.setGeometry(QtCore.QRect(330, 110, 31, 20))
        self.front_pitch_val.setObjectName(_fromUtf8("front_pitch_val"))
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(110, 140, 31, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(270, 140, 67, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.back_pitch_val = QtGui.QLabel(self.centralWidget)
        self.back_pitch_val.setGeometry(QtCore.QRect(330, 160, 31, 17))
        self.back_pitch_val.setObjectName(_fromUtf8("back_pitch_val"))
        self.label_13 = QtGui.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(110, 180, 41, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(270, 180, 41, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.side_left_val = QtGui.QLabel(self.centralWidget)
        self.side_left_val.setGeometry(QtCore.QRect(330, 190, 31, 17))
        self.side_left_val.setObjectName(_fromUtf8("side_left_val"))
        self.label_16 = QtGui.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(110, 220, 31, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.centralWidget)
        self.label_17.setGeometry(QtCore.QRect(280, 220, 41, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.side_right_val = QtGui.QLabel(self.centralWidget)
        self.side_right_val.setGeometry(QtCore.QRect(330, 230, 31, 17))
        self.side_right_val.setObjectName(_fromUtf8("side_right_val"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 712, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Thruster Panel", None))
        MainWindow.setToolTip(_translate("MainWindow", "Thruster_Panel", None))
        self.ThrustersInitialize.setText(_translate("MainWindow", "Thrusters Initialize", None))
        self.ThrustersOn.setText(_translate("MainWindow", "Thrusters On", None))
        self.label.setText(_translate("MainWindow", "front_pitch", None))
        self.label_2.setText(_translate("MainWindow", "back_pitch", None))
        self.label_3.setText(_translate("MainWindow", "side_left", None))
        self.label_4.setText(_translate("MainWindow", "side_right", None))
        self.label_5.setText(_translate("MainWindow", "Error notice!!!!", None))
        self.Thrustersoff.setText(_translate("MainWindow", "Thrusters off", None))
        self.poweroffOBC.setText(_translate("MainWindow", "Poweroff-OBC", None))
        self.rfront_pitch.setText(_translate("MainWindow", "front_pitch", None))
        self.rback_pitch.setText(_translate("MainWindow", "back_pitch", None))
        self.rside_left.setText(_translate("MainWindow", "side_left", None))
        self.rside_right.setText(_translate("MainWindow", "side_right", None))
        self.label_6.setText(_translate("MainWindow", "Thruster Direction  Reverse", None))
        self.OBCon.setText(_translate("MainWindow", "OBC-on", None))
        self.label_7.setText(_translate("MainWindow", "992", None))
        self.label_8.setText(_translate("MainWindow", "2000", None))
        self.front_pitch_val.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "992", None))
        self.label_11.setText(_translate("MainWindow", "2000", None))
        self.back_pitch_val.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "992", None))
        self.label_14.setText(_translate("MainWindow", "2000", None))
        self.side_left_val.setText(_translate("MainWindow", "0", None))
        self.label_16.setText(_translate("MainWindow", "992", None))
        self.label_17.setText(_translate("MainWindow", "2000", None))
        self.side_right_val.setText(_translate("MainWindow", "0", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Jul 19 07:17:32 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(712, 426)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Desktop/vehicle2.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.ThrustersInitialize = QtGui.QPushButton(self.centralWidget)
        self.ThrustersInitialize.setGeometry(QtCore.QRect(100, 10, 141, 27))
        self.ThrustersInitialize.setObjectName(_fromUtf8("ThrustersInitialize"))
        self.ThrustersOn = QtGui.QPushButton(self.centralWidget)
        self.ThrustersOn.setGeometry(QtCore.QRect(0, 40, 111, 27))
        self.ThrustersOn.setObjectName(_fromUtf8("ThrustersOn"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 110, 81, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 81, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 71, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 67, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.front_pitch_slider = QtGui.QSlider(self.centralWidget)
        self.front_pitch_slider.setGeometry(QtCore.QRect(110, 110, 181, 29))
        self.front_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.front_pitch_slider.setObjectName(_fromUtf8("front_pitch_slider"))
        self.back_pitch_slider = QtGui.QSlider(self.centralWidget)
        self.back_pitch_slider.setGeometry(QtCore.QRect(110, 150, 181, 29))
        self.back_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.back_pitch_slider.setObjectName(_fromUtf8("back_pitch_slider"))
        self.side_left_slider = QtGui.QSlider(self.centralWidget)
        self.side_left_slider.setGeometry(QtCore.QRect(110, 190, 181, 29))
        self.side_left_slider.setOrientation(QtCore.Qt.Horizontal)
        self.side_left_slider.setObjectName(_fromUtf8("side_left_slider"))
        self.side_right_slider = QtGui.QSlider(self.centralWidget)
        self.side_right_slider.setGeometry(QtCore.QRect(110, 230, 181, 29))
        self.side_right_slider.setOrientation(QtCore.Qt.Horizontal)
        self.side_right_slider.setObjectName(_fromUtf8("side_right_slider"))
        self.errorboard = QtGui.QTextBrowser(self.centralWidget)
        self.errorboard.setGeometry(QtCore.QRect(370, 60, 211, 181))
        self.errorboard.setObjectName(_fromUtf8("errorboard"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(370, 30, 111, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.Thrustersoff = QtGui.QPushButton(self.centralWidget)
        self.Thrustersoff.setGeometry(QtCore.QRect(230, 50, 101, 27))
        self.Thrustersoff.setObjectName(_fromUtf8("Thrustersoff"))
        self.poweroffOBC = QtGui.QPushButton(self.centralWidget)
        self.poweroffOBC.setGeometry(QtCore.QRect(590, 120, 111, 27))
        self.poweroffOBC.setObjectName(_fromUtf8("poweroffOBC"))
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(10, 290, 681, 61))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.rfront_pitch = QtGui.QPushButton(self.frame)
        self.rfront_pitch.setGeometry(QtCore.QRect(40, 20, 99, 27))
        self.rfront_pitch.setObjectName(_fromUtf8("rfront_pitch"))
        self.rback_pitch = QtGui.QPushButton(self.frame)
        self.rback_pitch.setGeometry(QtCore.QRect(210, 20, 99, 27))
        self.rback_pitch.setObjectName(_fromUtf8("rback_pitch"))
        self.rside_left = QtGui.QPushButton(self.frame)
        self.rside_left.setGeometry(QtCore.QRect(380, 20, 99, 27))
        self.rside_left.setObjectName(_fromUtf8("rside_left"))
        self.rside_right = QtGui.QPushButton(self.frame)
        self.rside_right.setGeometry(QtCore.QRect(540, 20, 99, 27))
        self.rside_right.setObjectName(_fromUtf8("rside_right"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(250, 260, 191, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.OBCon = QtGui.QPushButton(self.centralWidget)
        self.OBCon.setGeometry(QtCore.QRect(590, 170, 99, 27))
        self.OBCon.setObjectName(_fromUtf8("OBCon"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(110, 90, 31, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(270, 90, 41, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.front_pitch_val = QtGui.QLabel(self.centralWidget)
        self.front_pitch_val.setGeometry(QtCore.QRect(330, 110, 31, 20))
        self.front_pitch_val.setObjectName(_fromUtf8("front_pitch_val"))
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(110, 140, 31, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(270, 140, 67, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.back_pitch_val = QtGui.QLabel(self.centralWidget)
        self.back_pitch_val.setGeometry(QtCore.QRect(330, 160, 31, 17))
        self.back_pitch_val.setObjectName(_fromUtf8("back_pitch_val"))
        self.label_13 = QtGui.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(110, 180, 41, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(270, 180, 41, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.side_left_val = QtGui.QLabel(self.centralWidget)
        self.side_left_val.setGeometry(QtCore.QRect(330, 190, 31, 17))
        self.side_left_val.setObjectName(_fromUtf8("side_left_val"))
        self.label_16 = QtGui.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(110, 220, 31, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.centralWidget)
        self.label_17.setGeometry(QtCore.QRect(280, 220, 41, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.side_right_val = QtGui.QLabel(self.centralWidget)
        self.side_right_val.setGeometry(QtCore.QRect(330, 230, 31, 17))
        self.side_right_val.setObjectName(_fromUtf8("side_right_val"))
        self.checkBox = QtGui.QCheckBox(self.centralWidget)
        self.checkBox.setGeometry(QtCore.QRect(600, 50, 97, 22))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 712, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Thruster Panel", None))
        MainWindow.setToolTip(_translate("MainWindow", "Thruster_Panel", None))
        self.ThrustersInitialize.setText(_translate("MainWindow", "Thrusters Initialize", None))
        self.ThrustersOn.setText(_translate("MainWindow", "Thrusters On", None))
        self.label.setText(_translate("MainWindow", "front_pitch", None))
        self.label_2.setText(_translate("MainWindow", "back_pitch", None))
        self.label_3.setText(_translate("MainWindow", "side_left", None))
        self.label_4.setText(_translate("MainWindow", "side_right", None))
        self.label_5.setText(_translate("MainWindow", "Error notice!!!!", None))
        self.Thrustersoff.setText(_translate("MainWindow", "Thrusters off", None))
        self.poweroffOBC.setText(_translate("MainWindow", "Poweroff-OBC", None))
        self.rfront_pitch.setText(_translate("MainWindow", "front_pitch", None))
        self.rback_pitch.setText(_translate("MainWindow", "back_pitch", None))
        self.rside_left.setText(_translate("MainWindow", "side_left", None))
        self.rside_right.setText(_translate("MainWindow", "side_right", None))
        self.label_6.setText(_translate("MainWindow", "Thruster Direction  Reverse", None))
        self.OBCon.setText(_translate("MainWindow", "OBC-on", None))
        self.label_7.setText(_translate("MainWindow", "992", None))
        self.label_8.setText(_translate("MainWindow", "2000", None))
        self.front_pitch_val.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "992", None))
        self.label_11.setText(_translate("MainWindow", "2000", None))
        self.back_pitch_val.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "992", None))
        self.label_14.setText(_translate("MainWindow", "2000", None))
        self.side_left_val.setText(_translate("MainWindow", "0", None))
        self.label_16.setText(_translate("MainWindow", "992", None))
        self.label_17.setText(_translate("MainWindow", "2000", None))
        self.side_right_val.setText(_translate("MainWindow", "0", None))
        self.checkBox.setText(_translate("MainWindow", "run mode", None))

