// Generated by gencpp from file vn_100/auvcontrol.msg
// DO NOT EDIT!


#ifndef VN_100_MESSAGE_AUVCONTROL_H
#define VN_100_MESSAGE_AUVCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vn_100
{
template <class ContainerAllocator>
struct auvcontrol_
{
  typedef auvcontrol_<ContainerAllocator> Type;

  auvcontrol_()
    : msg(0)  {
    }
  auvcontrol_(const ContainerAllocator& _alloc)
    : msg(0)  {
    }



   typedef uint16_t _msg_type;
  _msg_type msg;




  typedef boost::shared_ptr< ::vn_100::auvcontrol_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vn_100::auvcontrol_<ContainerAllocator> const> ConstPtr;

}; // struct auvcontrol_

typedef ::vn_100::auvcontrol_<std::allocator<void> > auvcontrol;

typedef boost::shared_ptr< ::vn_100::auvcontrol > auvcontrolPtr;
typedef boost::shared_ptr< ::vn_100::auvcontrol const> auvcontrolConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vn_100::auvcontrol_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vn_100::auvcontrol_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vn_100

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'vn_100': ['/home/opp/Documents/auv-nitr/src/vn_100/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vn_100::auvcontrol_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vn_100::auvcontrol_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vn_100::auvcontrol_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vn_100::auvcontrol_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vn_100::auvcontrol_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vn_100::auvcontrol_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vn_100::auvcontrol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f3267e4c6a857ad880bfaf772c93116";
  }

  static const char* value(const ::vn_100::auvcontrol_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f3267e4c6a857adULL;
  static const uint64_t static_value2 = 0x880bfaf772c93116ULL;
};

template<class ContainerAllocator>
struct DataType< ::vn_100::auvcontrol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vn_100/auvcontrol";
  }

  static const char* value(const ::vn_100::auvcontrol_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vn_100::auvcontrol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 msg\n\
";
  }

  static const char* value(const ::vn_100::auvcontrol_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vn_100::auvcontrol_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct auvcontrol_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vn_100::auvcontrol_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vn_100::auvcontrol_<ContainerAllocator>& v)
  {
    s << indent << "msg: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VN_100_MESSAGE_AUVCONTROL_H
