// Generated by gencpp from file vn_100/depth_srvResponse.msg
// DO NOT EDIT!


#ifndef VN_100_MESSAGE_DEPTH_SRVRESPONSE_H
#define VN_100_MESSAGE_DEPTH_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vn_100
{
template <class ContainerAllocator>
struct depth_srvResponse_
{
  typedef depth_srvResponse_<ContainerAllocator> Type;

  depth_srvResponse_()
    : output(0.0)  {
    }
  depth_srvResponse_(const ContainerAllocator& _alloc)
    : output(0.0)  {
    }



   typedef float _output_type;
  _output_type output;




  typedef boost::shared_ptr< ::vn_100::depth_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vn_100::depth_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct depth_srvResponse_

typedef ::vn_100::depth_srvResponse_<std::allocator<void> > depth_srvResponse;

typedef boost::shared_ptr< ::vn_100::depth_srvResponse > depth_srvResponsePtr;
typedef boost::shared_ptr< ::vn_100::depth_srvResponse const> depth_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vn_100::depth_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vn_100::depth_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vn_100

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'vn_100': ['/home/opp/Documents/auv-nitr/src/vn_100/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vn_100::depth_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vn_100::depth_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vn_100::depth_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vn_100::depth_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vn_100::depth_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vn_100::depth_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vn_100::depth_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc04e8385a5c2f792e8299232db8e2eb";
  }

  static const char* value(const ::vn_100::depth_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc04e8385a5c2f79ULL;
  static const uint64_t static_value2 = 0x2e8299232db8e2ebULL;
};

template<class ContainerAllocator>
struct DataType< ::vn_100::depth_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vn_100/depth_srvResponse";
  }

  static const char* value(const ::vn_100::depth_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vn_100::depth_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 output\n\
\n\
";
  }

  static const char* value(const ::vn_100::depth_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vn_100::depth_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct depth_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vn_100::depth_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vn_100::depth_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<float>::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VN_100_MESSAGE_DEPTH_SRVRESPONSE_H
