// Generated by gencpp from file vn_100/depth_srv.msg
// DO NOT EDIT!


#ifndef VN_100_MESSAGE_DEPTH_SRV_H
#define VN_100_MESSAGE_DEPTH_SRV_H

#include <ros/service_traits.h>


#include <vn_100/depth_srvRequest.h>
#include <vn_100/depth_srvResponse.h>


namespace vn_100
{

struct depth_srv
{

typedef depth_srvRequest Request;
typedef depth_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct depth_srv
} // namespace vn_100


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vn_100::depth_srv > {
  static const char* value()
  {
    return "02afbbc686e2c044c6d3ef5d5a4f3cd3";
  }

  static const char* value(const ::vn_100::depth_srv&) { return value(); }
};

template<>
struct DataType< ::vn_100::depth_srv > {
  static const char* value()
  {
    return "vn_100/depth_srv";
  }

  static const char* value(const ::vn_100::depth_srv&) { return value(); }
};


// service_traits::MD5Sum< ::vn_100::depth_srvRequest> should match 
// service_traits::MD5Sum< ::vn_100::depth_srv > 
template<>
struct MD5Sum< ::vn_100::depth_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vn_100::depth_srv >::value();
  }
  static const char* value(const ::vn_100::depth_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vn_100::depth_srvRequest> should match 
// service_traits::DataType< ::vn_100::depth_srv > 
template<>
struct DataType< ::vn_100::depth_srvRequest>
{
  static const char* value()
  {
    return DataType< ::vn_100::depth_srv >::value();
  }
  static const char* value(const ::vn_100::depth_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vn_100::depth_srvResponse> should match 
// service_traits::MD5Sum< ::vn_100::depth_srv > 
template<>
struct MD5Sum< ::vn_100::depth_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vn_100::depth_srv >::value();
  }
  static const char* value(const ::vn_100::depth_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vn_100::depth_srvResponse> should match 
// service_traits::DataType< ::vn_100::depth_srv > 
template<>
struct DataType< ::vn_100::depth_srvResponse>
{
  static const char* value()
  {
    return DataType< ::vn_100::depth_srv >::value();
  }
  static const char* value(const ::vn_100::depth_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VN_100_MESSAGE_DEPTH_SRV_H
