// Generated by gencpp from file vn_100/ins_data.msg
// DO NOT EDIT!


#ifndef VN_100_MESSAGE_INS_DATA_H
#define VN_100_MESSAGE_INS_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace vn_100
{
template <class ContainerAllocator>
struct ins_data_
{
  typedef ins_data_<ContainerAllocator> Type;

  ins_data_()
    : header()
    , YPR()
    , quat_data()  {
      quat_data.assign(0.0);
  }
  ins_data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , YPR(_alloc)
    , quat_data()  {
      quat_data.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _YPR_type;
  _YPR_type YPR;

   typedef boost::array<float, 4>  _quat_data_type;
  _quat_data_type quat_data;




  typedef boost::shared_ptr< ::vn_100::ins_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vn_100::ins_data_<ContainerAllocator> const> ConstPtr;

}; // struct ins_data_

typedef ::vn_100::ins_data_<std::allocator<void> > ins_data;

typedef boost::shared_ptr< ::vn_100::ins_data > ins_dataPtr;
typedef boost::shared_ptr< ::vn_100::ins_data const> ins_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vn_100::ins_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vn_100::ins_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vn_100

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'vn_100': ['/home/opp/Documents/auv-nitr/src/vn_100/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vn_100::ins_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vn_100::ins_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vn_100::ins_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vn_100::ins_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vn_100::ins_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vn_100::ins_data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vn_100::ins_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a03b8a926f3035d530c063d87d10078";
  }

  static const char* value(const ::vn_100::ins_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a03b8a926f3035dULL;
  static const uint64_t static_value2 = 0x530c063d87d10078ULL;
};

template<class ContainerAllocator>
struct DataType< ::vn_100::ins_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vn_100/ins_data";
  }

  static const char* value(const ::vn_100::ins_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vn_100::ins_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header        header\n\
geometry_msgs/Vector3  YPR\n\
float32[4]              quat_data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::vn_100::ins_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vn_100::ins_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.YPR);
      stream.next(m.quat_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ins_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vn_100::ins_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vn_100::ins_data_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "YPR: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.YPR);
    s << indent << "quat_data[]" << std::endl;
    for (size_t i = 0; i < v.quat_data.size(); ++i)
    {
      s << indent << "  quat_data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.quat_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VN_100_MESSAGE_INS_DATA_H
