// Generated by gencpp from file vn_100/YPR.msg
// DO NOT EDIT!


#ifndef VN_100_MESSAGE_YPR_H
#define VN_100_MESSAGE_YPR_H

#include <ros/service_traits.h>


#include <vn_100/YPRRequest.h>
#include <vn_100/YPRResponse.h>


namespace vn_100
{

struct YPR
{

typedef YPRRequest Request;
typedef YPRResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct YPR
} // namespace vn_100


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vn_100::YPR > {
  static const char* value()
  {
    return "38523f96e5f55f0457623ec9a8c6ca22";
  }

  static const char* value(const ::vn_100::YPR&) { return value(); }
};

template<>
struct DataType< ::vn_100::YPR > {
  static const char* value()
  {
    return "vn_100/YPR";
  }

  static const char* value(const ::vn_100::YPR&) { return value(); }
};


// service_traits::MD5Sum< ::vn_100::YPRRequest> should match 
// service_traits::MD5Sum< ::vn_100::YPR > 
template<>
struct MD5Sum< ::vn_100::YPRRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vn_100::YPR >::value();
  }
  static const char* value(const ::vn_100::YPRRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vn_100::YPRRequest> should match 
// service_traits::DataType< ::vn_100::YPR > 
template<>
struct DataType< ::vn_100::YPRRequest>
{
  static const char* value()
  {
    return DataType< ::vn_100::YPR >::value();
  }
  static const char* value(const ::vn_100::YPRRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vn_100::YPRResponse> should match 
// service_traits::MD5Sum< ::vn_100::YPR > 
template<>
struct MD5Sum< ::vn_100::YPRResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vn_100::YPR >::value();
  }
  static const char* value(const ::vn_100::YPRResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vn_100::YPRResponse> should match 
// service_traits::DataType< ::vn_100::YPR > 
template<>
struct DataType< ::vn_100::YPRResponse>
{
  static const char* value()
  {
    return DataType< ::vn_100::YPR >::value();
  }
  static const char* value(const ::vn_100::YPRResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VN_100_MESSAGE_YPR_H
