// Generated by gencpp from file vn_100/YPRRequest.msg
// DO NOT EDIT!


#ifndef VN_100_MESSAGE_YPRREQUEST_H
#define VN_100_MESSAGE_YPRREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vn_100
{
template <class ContainerAllocator>
struct YPRRequest_
{
  typedef YPRRequest_<ContainerAllocator> Type;

  YPRRequest_()
    : ins()  {
    }
  YPRRequest_(const ContainerAllocator& _alloc)
    : ins(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ins_type;
  _ins_type ins;




  typedef boost::shared_ptr< ::vn_100::YPRRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vn_100::YPRRequest_<ContainerAllocator> const> ConstPtr;

}; // struct YPRRequest_

typedef ::vn_100::YPRRequest_<std::allocator<void> > YPRRequest;

typedef boost::shared_ptr< ::vn_100::YPRRequest > YPRRequestPtr;
typedef boost::shared_ptr< ::vn_100::YPRRequest const> YPRRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vn_100::YPRRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vn_100::YPRRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vn_100

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'vn_100': ['/home/opp/Documents/auv-nitr/src/vn_100/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vn_100::YPRRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vn_100::YPRRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vn_100::YPRRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vn_100::YPRRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vn_100::YPRRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vn_100::YPRRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vn_100::YPRRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6963138aeb73c6323225ba70d5e9e2b";
  }

  static const char* value(const ::vn_100::YPRRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6963138aeb73c63ULL;
  static const uint64_t static_value2 = 0x23225ba70d5e9e2bULL;
};

template<class ContainerAllocator>
struct DataType< ::vn_100::YPRRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vn_100/YPRRequest";
  }

  static const char* value(const ::vn_100::YPRRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vn_100::YPRRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string   ins\n\
";
  }

  static const char* value(const ::vn_100::YPRRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vn_100::YPRRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ins);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct YPRRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vn_100::YPRRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vn_100::YPRRequest_<ContainerAllocator>& v)
  {
    s << indent << "ins: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ins);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VN_100_MESSAGE_YPRREQUEST_H
